### ISSUE TITLE
Fails to build with glib >= 2.80

### ISSUE THREAD

**Issue by jbeich** [gtkd-developers/GlibD#20]
Regressed by https://github.com/gnome/glib/commit/7cb953dab8d0. From [error log](https://pkg-status.freebsd.org/package18/data/140amd64-default-foo/2024-03-08_20h16m31s/logs/errors/glibd-2.4.3.log):
```d
../_build/generated/gio/Socket.d(1239): Error: function `gio.c.functions.g_socket_receive_bytes_from(GSocket* socket, GSocketAddress** address, ulong size, long timeoutUs, GCancellable* cancellable, GError** err)` is not callable using argument types `(GSocket*, GSocketAddress*, ulong, long, GCancellable*, GError**)`
../_build/generated/gio/Socket.d(1239):        cannot pass argument `address is null ? cast(GSocketAddress*)null : address.getSocketAddressStruct(false)` of type `GSocketAddress*` to parameter `GSocketAddress** address`
```

**Comment by MikeWey** [comment]
I looks like this error is no longer present in the release version of glib 2,80 / gobject-introspection 1.80.1
