### ISSUE TITLE
Needs update for glib 2.89.3

### ISSUE THREAD

**Issue by jbicha** [gtkd-developers/GlibD#26]
- glib-d 2.4.3
- Debian Unstable (with glib2.0 from experimental) or Ubuntu 26.10 (with glib2.0 from stonking-proposed)
- glib 2.89.3

glib-d fails to build with glib 2.89.3. glib 2.89.3 is part of GNOME 51 Beta. GNOME 51 is [scheduled for release](https://release.gnome.org/calendar/) 16 September.

Build log excerpt
-----
```
[2/354] ldc2 -I=libglibd-2.0.so.2.4.1.p -I=. -I=.. -I=generated -I=../generated
 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
 -I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid -enable-color
 -wi -release -wi -g -O2 -fcf-protection=full -relocation-model=pic
 -makedeps=libglibd-2.0.so.2.4.1.p/obj-x86_64-linux-gnu_generated_glib_AsyncQueue.d.o.deps
 -of=libglibd-2.0.so.2.4.1.p/obj-x86_64-linux-gnu_generated_glib_AsyncQueue.d.o
 -c ../obj-x86_64-linux-gnu/generated/glib/AsyncQueue.d
FAILED: [code=1] libglibd-2.0.so.2.4.1.p/obj-x86_64-linux-gnu_generated_glib_AsyncQueue.d.o
ldc2 -I=libglibd-2.0.so.2.4.1.p -I=. -I=.. -I=generated -I=../generated
 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
 -I/usr/include/sysprof-6 -I/usr/include/libmount -I/usr/include/blkid -enable-color
 -wi -release -wi -g -O2 -fcf-protection=full -relocation-model=pic
 -makedeps=libglibd-2.0.so.2.4.1.p/obj-x86_64-linux-gnu_generated_glib_AsyncQueue.d.o.deps
 -of=libglibd-2.0.so.2.4.1.p/obj-x86_64-linux-gnu_generated_glib_AsyncQueue.d.o -c
 ../obj-x86_64-linux-gnu/generated/glib/AsyncQueue.d
generated/glib/c/functions.d(1121): Error: undefined identifier `uint64_t`
    int g_source_get_ready_time_ns(GSource* source, uint64_t* readyTime);
                                                    ^
generated/glib/c/functions.d(1123): Error: undefined identifier `uint64_t`
    uint64_t g_source_get_time_ns(GSource* source);
    ^
generated/glib/c/functions.d(1139): Error: undefined identifier `uint64_t`
    void g_source_set_ready_time_ns(GSource* source, uint64_t readyTime);
```

Full log
-----
https://autopkgtest.ubuntu.com/packages/g/glib-d/stonking/amd64

Other info
----
This issue was reported to Debian as https://bugs.debian.org/1143806
