### ISSUE TITLE
glibd fails to build on Fedora 33 with glib2 2.66.0

### ISSUE THREAD

**Issue by Conan-Kudo** [gtkd-developers/GlibD#10]
When trying to build glibd on Fedora 33 with glib2 2.65.2, it fails with the following error:

```
[7/337] ldc2 -enable-color -release -w -g -O1 -relocation-model=pic -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I=../generated -I=generated -I=.. -I=. -I=libglibd-2.0.so.2.2.0.p -of=libglibd-2.0.so.2.2.0.p/x86_64-redhat-linux-gnu_generated_glib_BookmarkFile.d.o -c ../x86_64-redhat-linux-gnu/generated/glib/BookmarkFile.d
FAILED: libglibd-2.0.so.2.2.0.p/x86_64-redhat-linux-gnu_generated_glib_BookmarkFile.d.o
ldc2 -enable-color -release -w -g -O1 -relocation-model=pic -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I=../generated -I=generated -I=.. -I=. -I=libglibd-2.0.so.2.2.0.p -of=libglibd-2.0.so.2.2.0.p/x86_64-redhat-linux-gnu_generated_glib_BookmarkFile.d.o -c ../x86_64-redhat-linux-gnu/generated/glib/BookmarkFile.d
../x86_64-redhat-linux-gnu/generated/glib/BookmarkFile.d(240): Error: function glib.c.functions.g_bookmark_file_get_application_info(GBookmarkFile* bookmark, const(char)* uri, const(char)* name, char** exec, uint* count, GDateTime** stamp, GError** err) is not callable using argument types (GBookmarkFile*, char*, char*, char**, uint*, GDateTime*, GError**)
../x86_64-redhat-linux-gnu/generated/glib/BookmarkFile.d(240):        cannot pass argument stamp is cast(DateTime)null ? cast(GDateTime*)null : stamp.getDateTimeStruct(false) of type GDateTime* to parameter GDateTime** stamp
```

**Comment by MikeWey** [comment]
Which version of gobject-inrospection is installed?

**Comment by Conan-Kudo** [comment]
gobject-introspection-1.64.1

**Comment by Conan-Kudo** [comment]
@MikeWey Any chance you have figured out what's wrong here?

**Comment by Conan-Kudo** [comment]
glib2 2.66.0 and gobject-introspection 1.66.0 landed, and I get a new interesting error:

```
meson.build:37:4: ERROR: Problem encountered: Unable to build D intefaces from GIR:
Error /usr/share/gir-1.0/GLib-2.0.gir(51578): Unexpected tag: docsection in GirPackage: glib
```

**Comment by MikeWey** [comment]
For the first one i didn't look yet due to time constraints.

For the new error it looks like they updated gir files, so we now have to take a look at what we need to do with the new information, either skip it or use it if needed.

**Comment by MikeWey** [comment]
I've updated gir-to-d for the added docsection. i also can't reproduce the first error locally with gobject-introspection 1.66. Still have to try on fedora 33.
