### ISSUE TITLE
glibd fails to build on Fedora 34 with glib2 2.68

### ISSUE THREAD

**Issue by Conan-Kudo** [gtkd-developers/GlibD#11]
When trying to build glibd on Fedora 34 with glib2 2.67.4 and gobject-introspection 1.66.1, it fails with the following error:

```
[7/340] ldc2 -I=libglibd-2.0.so.2.3.0.p -I=. -I=.. -I=generated -I=../generated -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -enable-color -wi -release -w -g -O1 -relocation-model=pic -of=libglibd-2.0.so.2.3.0.p/x86_64-redhat-linux-gnu_generated_glib_BookmarkFile.d.o -c ../x86_64-redhat-linux-gnu/generated/glib/BookmarkFile.d
FAILED: libglibd-2.0.so.2.3.0.p/x86_64-redhat-linux-gnu_generated_glib_BookmarkFile.d.o 
ldc2 -I=libglibd-2.0.so.2.3.0.p -I=. -I=.. -I=generated -I=../generated -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -enable-color -wi -release -w -g -O1 -relocation-model=pic -of=libglibd-2.0.so.2.3.0.p/x86_64-redhat-linux-gnu_generated_glib_BookmarkFile.d.o -c ../x86_64-redhat-linux-gnu/generated/glib/BookmarkFile.d
generated/glib/TimeZone.d(163): Error: constructor glib.TimeZone.TimeZone.this(string identifier) conflicts with previous declaration at generated/glib/TimeZone.d(150)
```

**Comment by Conan-Kudo** [comment]
With this patch, it fails with the following error:

```
[12/340] ldc2 -I=libglibd-2.0.so.2.3.0.p -I=. -I=.. -I=generated -I=../generated -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -enable-color -wi -release -w -g -O1 -relocation-model=pic -makedeps=libglibd-2.0.so.2.3.0.p/x86_64-redhat-linux-gnu_generated_glib_DateTime.d.o.deps -of=libglibd-2.0.so.2.3.0.p/x86_64-redhat-linux-gnu_generated_glib_DateTime.d.o -c ../x86_64-redhat-linux-gnu/generated/glib/DateTime.d
FAILED: libglibd-2.0.so.2.3.0.p/x86_64-redhat-linux-gnu_generated_glib_DateTime.d.o
ldc2 -I=libglibd-2.0.so.2.3.0.p -I=. -I=.. -I=generated -I=../generated -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -enable-color -wi -release -w -g -O1 -relocation-model=pic -makedeps=libglibd-2.0.so.2.3.0.p/x86_64-redhat-linux-gnu_generated_glib_DateTime.d.o.deps -of=libglibd-2.0.so.2.3.0.p/x86_64-redhat-linux-gnu_generated_glib_DateTime.d.o -c ../x86_64-redhat-linux-gnu/generated/glib/DateTime.d
../x86_64-redhat-linux-gnu/generated/glib/DateTime.d(161): Error: function glib.DateTime.DateTime.equal(DateTime dt2) is not callable using argument types (DateTime, DateTime)
../x86_64-redhat-linux-gnu/generated/glib/DateTime.d(161):        expected 1 argument(s), not 2
../x86_64-redhat-linux-gnu/generated/glib/DateTime.d(172): Error: function glib.DateTime.DateTime.compare(DateTime dt2) is not callable using argument types (DateTime, DateTime)
../x86_64-redhat-linux-gnu/generated/glib/DateTime.d(172):        expected 1 argument(s), not 2
```

Though now I'm building against glib2-2.68.

**Comment by Conan-Kudo** [comment]
This is also failing with current git master + the proposed patch with glib2 2.68.

**Comment by MikeWey** [comment]
With commit b22a87ee6f42806aff5f9173a24cd05995db6cb0 it should work with GLib 2.68 / Fedora 34.

**Comment by Conan-Kudo** [comment]
Yep, that fixed the build: https://bodhi.fedoraproject.org/updates/FEDORA-2021-c9bb0b0926
